steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/learning-gcp-22/test-app:$_VERSION
      - -t
      - gcr.io/learning-gcp-22/test-app:latest
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - gcr.io/learning-gcp-22/test-app
